name: Benchmark

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [14]

    steps:
    - uses: actions/checkout@v2

    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - run: npm install
    - run: npm run bench
    - run: npx jsonlint < benchmarks/result.txt > benchmarks/report.json

    - uses: actions/upload-artifact@v2
      with:
        path: benchmarks/report.json
